### ISSUE TITLE
Doesn't Build with Dune 2.6.0

### ISSUE THREAD

**Issue by rabidlogic** [astrada/ocamlfuse#14]
Don't really know much about ocaml or dune, but I have been unable to get this package to build for the last few days. When I try to install it through opam - it wants to downgrade my dune to 2.5.

```
[rabid@box ocamlfuse-master]$ opam list
# Packages matching: installed
# Name            # Installed # Synopsis
base-bigarray     base
base-threads      base
base-unix         base
dune              2.6.0       Fast, portable, and opinionated build system
dune-configurator 2.6.0       Helper library for gathering system configuration
dune-private-libs 2.6.0       Private libraries of Dune
ocaml             4.10.0      The OCaml compiler (virtual package)
ocaml-config      1           OCaml Switch Configuration
ocaml-system      4.10.0      The OCaml compiler (system version, from outside of opam)

[rabid@box ocamlfuse-master]$ dune build @install
File "lib/config/discover.ml", line 1, characters 6-12:
1 | open! Stdune
          ^^^^^^
Error: Unbound module Stdune
```

**Comment by astrada** [comment]
Yes, the PR #12 used a non-public dune API to implement the configurator, but in dune 2.6 that api was removed, or probably moved to dune-private-libs. The quick fix was to add a constraint to use dune up to 2.5.

**Comment by rabidlogic** [comment]
Thanks for the fix.
